# Generated by Django 3.1.3 on 2020-11-28 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Waren', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestellungInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bestellung_Nummer', models.CharField(max_length=100)),
                ('Bestellung_Add', models.CharField(max_length=200)),
                ('Bestellung_Empf', models.CharField(max_length=100)),
                ('Bestellung_Tel', models.CharField(max_length=100)),
                ('Bestellung_transkost', models.FloatField(default=3.99)),
                ('Bestellung_Anmerkung', models.CharField(max_length=1000)),
                ('Bestellung_Zustand', models.IntegerField(choices=[(1, 'Noch nicht bezahlen'), (2, 'Noch nicht geliefert'), (3, 'Geliefert'), (4, 'Zugestellt')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='BestellungDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ware_Meng', models.IntegerField()),
                ('Ware_Bestellung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Einkaufswagen.bestellunginfo')),
                ('Ware_Kate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Waren.warenkategorien')),
            ],
        ),
    ]
